"""Pure PowerShell-text builder for the lab-computer acquisition supervisor (D-88).

Text only -- no `subprocess`, no file I/O, no network. The lab computer must stay free
of any interpreted-language runtime (D-66), so the supervisor cannot be a script in
this package's own language that happens to run there; it is PowerShell text GENERATED
on a different machine by `dlc_link` and never executed by this package itself.

Kept boring on purpose (`38-07-PLAN.md` Task 1 action): parameters at the top as
`$var=` assignments with a comment naming each, then the ffmpeg argument array, then
the bounded restart loop -- a researcher with no other tooling on that machine has to
be able to read and debug this without help.
"""

# A conservative per-line character budget for the generated `$a=@(...)` / `$a+=@(...)`
# assignments. The plan's own paste-safety rule is "under 100 characters"; 90 leaves
# headroom for the `$a+=@(...)` wrapper itself and for one extra comma before the next
# token is appended, so the final rendered line never crosses 100.
_ARRAY_LINE_BUDGET = 90


def _ps_quote(token):
    """PowerShell single-quoted string literal: the only special case is an embedded
    single quote, doubled per PowerShell's own escaping rule."""
    return "'{}'".format(str(token).replace("'", "''"))


def _chunk_argv(argv):
    """Group the quoted argv tokens into lines that stay under `_ARRAY_LINE_BUDGET`,
    length-aware rather than a fixed token count -- a device name with spaces and
    brackets in it can be much longer than an ffmpeg flag, and a fixed count would
    either waste the budget on short tokens or overflow it on long ones."""
    groups = []
    current = []
    current_len = len("$a+=@(")
    for token in argv:
        quoted = _ps_quote(token)
        addition = len(quoted) + (1 if current else 0)  # ", " separator once non-empty
        if current and current_len + addition > _ARRAY_LINE_BUDGET:
            groups.append(current)
            current = []
            current_len = len("$a+=@(")
        current.append(quoted)
        current_len += addition
    if current:
        groups.append(current)
    return groups


def _argv_array_lines(argv):
    lines = []
    for index, group in enumerate(_chunk_argv(argv)):
        prefix = "$a=@(" if index == 0 else "$a+=@("
        lines.append("{}{})".format(prefix, ",".join(group)))
    return lines


def build_supervisor_ps1(ffmpeg_path_var, argv, working_dir_var, log_dir_var,
                          max_restarts, restart_delay_s):
    """Returns the supervisor's PowerShell text.

    `ffmpeg_path_var`, `working_dir_var`, `log_dir_var` are the literal PowerShell
    right-hand-side expressions to assign to `$ff` / `$wd` / `$lg` (e.g. a quoted path
    or an `$env:USERPROFILE`-based expression) -- this module takes no position on
    where ffmpeg lives or where segments land; that is the caller's decision, never a
    hardcoded literal in this function.

    `argv` is the ffmpeg argument list (as from `acquire.build_ffmpeg_argv`), excluding
    the executable itself. Every attempt gets its OWN `-RedirectStandardError` path,
    named with a timestamp and the attempt number, because that log file is witness 3
    of the completeness test and `-RedirectStandardError` truncates on each new run --
    reusing one path across attempts would lose every attempt but the last.
    """
    lines = [
        "# GENERATED by dlc-link-relay --print supervisor (dlc_link.acquire_supervisor).",
        "# Hand edits drift from the generator -- regenerate instead of editing this file.",
        "# See dlc_link/RUNBOOK.md, ACQUISITION section, for what each piece is for.",
        "",
        "$ff = {}".format(ffmpeg_path_var),
        "$wd = {}".format(working_dir_var),
        "$lg = {}".format(log_dir_var),
        "$maxRestarts = {}".format(int(max_restarts)),
        "$restartDelaySec = {}".format(restart_delay_s),
        "",
        "# The ffmpeg argument array. Each line stays short on purpose -- a long single",
        "# line wraps on paste in a Windows terminal, which cost two real failures in the",
        "# 2026-09-10 rig session (38-HARDWARE-VALIDATION.md, rule 3, defect 8.3).",
    ]
    lines += _argv_array_lines(argv)
    lines += [
        "",
        "New-Item -ItemType Directory -Force -Path $wd,$lg | Out-Null",
        "",
        "$attempt = 0",
        "$lastExit = $null",
        "while ($attempt -lt $maxRestarts) {",
        "    $attempt++",
        "    if ($attempt -gt 1) {",
        '        Write-Host "restart attempt $attempt after previous exit code $lastExit"',
        "        Start-Sleep -Seconds $restartDelaySec",
        "    }",
        '    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"',
        '    $err = Join-Path $lg "acq-$stamp-attempt$attempt.err.log"',
        "    $sp = @{FilePath=$ff; ArgumentList=$a; WorkingDirectory=$wd}",
        "    $proc = Start-Process @sp -NoNewWindow -Wait -PassThru -RedirectStandardError $err",
        "    $lastExit = $proc.ExitCode",
        "}",
        'Write-Host "gave up after $attempt attempts; last exit code $lastExit; log $err"',
        'Write-Host "segment directory: $wd"',
        'Write-Host "log directory: $lg"',
    ]
    return "\n".join(lines) + "\n"
