"""Loads a generated `<source_id>_signals.py` map by filesystem path (D-12).

This module has exactly one job: read what `dlc-link-generate` emitted. It never
re-derives a bodypart-string-to-identifier transform, and never rebuilds the
bodypart-to-signal-name mapping -- that transform has one declaration site
(`dlc_link.names`) and is called only by the generator. The adapter (`dlc_link.processor`)
imports the record this module returns and indexes the pose array with it directly.

`assert_pairs_with` is the anti-divergence check plan 35-06's runbook and
`dlc-link-live --verify-lib` both use: it proves the map a sender loaded and the lib
actually deployed to the Pi came from the SAME `dlc-link-generate` invocation. A silent
mismatch here is not a loud error on the wire -- it is total, invisible failure: every
signal name the map declares that does not match what the deployed lib's class actually
exposes is dropped Pi-side as `unknown_name`, with nothing visible from the sender.
"""
import hashlib
import importlib.util

from dlc_link.names import flat_signal_names

# Every constant `dlc_link.templates.render_signal_map` unconditionally emits. A file
# missing any of these was not produced by dlc-link-generate, or was hand-edited after
# generation -- either way it is refused, never partially trusted.
_REQUIRED_CONSTANTS = (
    "SOURCE_ID",
    "CLASS_NAME",
    "BODYPARTS",
    "SIGNALS",
    "SIGNAL_NAMES",
    "STALE_AFTER_MS",
    "ENGINE",
    "SOURCE_FORMAT",
    "CONFIG_PATH",
    "CONFIG_SHA256",
    "GENERATED_AT",
    "GENERATOR_VERSION",
    "LIB_SHA256",
)

_DO_NOT_HAND_EDIT = (
    "this file must be generated by dlc-link-generate and must not be hand-edited"
)


class SignalMapError(Exception):
    """Raised for every refusal in this module. Always names the file path involved."""


class SignalMapRecord:
    """Plain, attribute-only view over every UPPERCASE constant a generated signal-map
    module defines (`SOURCE_ID`, `SIGNALS`, `POSE_ORDER`, `LIB_SHA256`, ...). Never a
    dict -- `dlc_link.processor` reads `smap.SIGNALS`, `smap.POSE_ORDER`, never a
    subscript, so a missing attribute fails loudly with `AttributeError` at the call
    site rather than a silent `KeyError`-shaped default.
    """

    def __init__(self, values):
        self.__dict__.update(values)


def _load_module(path):
    spec = importlib.util.spec_from_file_location("dlc_link_generated_signal_map", str(path))
    if spec is None or spec.loader is None:
        raise SignalMapError(
            "{}: could not build an import spec for this file -- {}".format(
                path, _DO_NOT_HAND_EDIT
            )
        )
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except Exception as exc:
        raise SignalMapError(
            "{}: failed to execute as Python ({}: {}) -- {}".format(
                path, type(exc).__name__, exc, _DO_NOT_HAND_EDIT
            )
        )
    return module


def _validate_signals(path, signals):
    if not isinstance(signals, dict):
        raise SignalMapError(
            "{}: SIGNALS must be a dict, got {!r} -- {}".format(
                path, type(signals).__name__, _DO_NOT_HAND_EDIT
            )
        )
    seen_index_owner = {}
    expected_names = set()
    for bodypart, entry in signals.items():
        if not isinstance(entry, dict) or "index" not in entry or "signals" not in entry:
            raise SignalMapError(
                "{}: SIGNALS[{!r}] is missing 'index' or 'signals' -- {}".format(
                    path, bodypart, _DO_NOT_HAND_EDIT
                )
            )
        index = entry["index"]
        if not isinstance(index, int) or isinstance(index, bool):
            raise SignalMapError(
                "{}: SIGNALS[{!r}]['index'] must be an int, got {!r} -- {}".format(
                    path, bodypart, index, _DO_NOT_HAND_EDIT
                )
            )
        if index in seen_index_owner:
            raise SignalMapError(
                "{}: bodyparts {!r} and {!r} share index {} -- {}".format(
                    path, seen_index_owner[index], bodypart, index, _DO_NOT_HAND_EDIT
                )
            )
        seen_index_owner[index] = bodypart
        expected_names.update(entry["signals"].values())
    return expected_names


def load_signal_map(path):
    """Import the generated `<source_id>_signals.py` at `path` and return a
    `SignalMapRecord`. Raises `SignalMapError`, always naming `path`, when: a required
    constant is missing; `SIGNALS` is not a dict of the expected shape; any `index` is
    not an int; two bodyparts share an `index`; or `SIGNAL_NAMES` does not equal the set
    of names `SIGNALS` itself declares.
    """
    module = _load_module(path)
    values = {name: getattr(module, name) for name in dir(module) if name.isupper()}

    missing = [name for name in _REQUIRED_CONSTANTS if name not in values]
    if missing:
        raise SignalMapError(
            "{}: missing required constant(s) {!r} -- {}".format(
                path, missing, _DO_NOT_HAND_EDIT
            )
        )

    expected_names = _validate_signals(path, values["SIGNALS"])

    if not isinstance(values["SIGNAL_NAMES"], list):
        raise SignalMapError(
            "{}: SIGNAL_NAMES must be a list, got {!r} -- {}".format(
                path, type(values["SIGNAL_NAMES"]).__name__, _DO_NOT_HAND_EDIT
            )
        )
    if set(values["SIGNAL_NAMES"]) != expected_names:
        # Cross-checked against SIGNALS's own declared names -- the same flattening the
        # generator itself runs (dlc_link.names' one flattening helper), never a
        # bodypart-to-identifier re-derivation.
        actual = set(flat_signal_names(values["SIGNALS"]))
        if actual != set(values["SIGNAL_NAMES"]):
            raise SignalMapError(
                "{}: SIGNAL_NAMES {!r} does not equal the names derivable from SIGNALS "
                "{!r} -- {}".format(
                    path, sorted(values["SIGNAL_NAMES"]), sorted(expected_names), _DO_NOT_HAND_EDIT
                )
            )

    values.setdefault("POSE_ORDER", [])
    values.setdefault("POSE_ORDER_SOURCE", None)
    values.setdefault("BODYPART_CLASS", {})
    return SignalMapRecord(values)


def assert_pairs_with(smap, lib_source_text):
    """Raise `SignalMapError` unless `smap.LIB_SHA256` equals the sha256 of
    `lib_source_text`. A mismatch means the map and the deployed lib came from DIFFERENT
    `dlc-link-generate` invocations. Consequence, stated because it is not obvious from
    the wire: every frame whose name is not declared on the Pi is dropped as
    `unknown_name` and that drop is invisible from the sender.
    """
    actual = hashlib.sha256(lib_source_text.encode("utf-8")).hexdigest()
    if actual != smap.LIB_SHA256:
        raise SignalMapError(
            "signal map's LIB_SHA256 ({}) does not match this lib source's sha256 ({}) -- "
            "the map and the deployed lib came from different generator invocations. "
            "Consequence: every frame whose name is not declared on the Pi is dropped as "
            "unknown_name and is invisible from the sender.".format(smap.LIB_SHA256, actual)
        )
