"""The lib-source and signal-map source templates, and the emitted liveness hook (D-11..D-13).

Pure string rendering only -- no file I/O, no argparse, so `dlc_link.generate.generate()`
and this module's own callers drive it directly and `dlc_link/tests/test_generate.py`
exercises it without touching disk.

**T-35-09 (this plan's threat register): every researcher-controlled value that ends up
inside a docstring is embedded via a WHOLE-BLOCK `repr()`, never raw string
concatenation.** A stray triple quote or backslash in a config path would otherwise
terminate the enclosing `\"\"\"..\"\"\"` literal early and corrupt the emitted source --
this is a code-injection seam into something the Pi will `exec`. `repr()` of an
arbitrary Python `str` is *always* a syntactically valid, self-contained string literal
(`eval(repr(s)) == s` for every `str` `s`), so building the FULL docstring text first (a
plain runtime string, computed here, never itself parsed as source) and then emitting
`repr(that_text)` as the literal guarantees valid output regardless of content. Compare:
manually writing `\"\"\"...{value}...\"\"\"` with an f-string would leave a real collision
window whenever `value` contains `\"\"\"`. Every non-docstring emitted value (identifiers,
dict/list constants in the signal map) goes through `repr()` too, for the same reason and
with the same guarantee -- see `render_signal_map` below.
"""
from dlc_link.names import flat_signal_names

# Verbatim from plan 35-02's canonical liveness hook
# (.planning/phases/35-deeplabcut-keypoint-likelihood-integration/fixtures/liveness_hook_snippet.py),
# emitted as a class-level method body -- the WORKAROUND for Phase 31's Defect B
# (D-49..D-51), not a sanctioned exemption. Do not re-derive; this text must match that
# fixture's function body character-for-character (module docstring above it is NOT
# reproduced here -- only the function itself becomes part of the emitted class).
LIVENESS_HOOK_METHOD = '''\
def liveness_hook(self, last_msg_ts_ms, now_ms, stale_ms):
    """The passed-in `now_ms` is not used because it is `time.time()`-derived
    (`external_hardware_binding.py:_now_ms()`) while `last_msg_ts_ms` is one-clock-derived on
    the mics_core stack, so subtracting them crosses clock domains; on the pi-mirror stack this
    hook is numerically identical to `default_liveness` because both sides are `time.time()`
    there (`pi-mirror/.../external_hardware_ingress.py` stamps `int(time.time() * 1000)`).
    """
    if last_msg_ts_ms is None:
        return False
    try:
        # Imported here, not at module scope: a module-level import would run at lib-exec
        # time (this file is `exec`'d from `hardware_lib_versions.source_code`), before
        # `autopilot.hardware.external_hardware_ingress` is necessarily importable.
        from autopilot.hardware.external_hardware_ingress import now_ms as ingress_now_ms
        current = ingress_now_ms()
    except Exception:
        # Degrade to the substrate default rather than raising into the LivenessPoller,
        # which runs on its own daemon thread but whose exceptions would otherwise silently
        # stop the poll (T-35-06).
        current = now_ms

    if not getattr(self, "_liveness_hook_logged_once", False):
        self._liveness_hook_logged_once = True
        # One-shot diagnostic: measures the actual offset between the two clocks on a real
        # rig run, landing in the pilot journal via self.logger (never print -- this runs
        # inside the pilot process, not a script with a controlling terminal).
        self.logger.warning(
            "liveness_hook: one-shot clock check (last_msg_ts_ms=%s, now_ms=%s, "
            "ingress_now_ms=%s)", last_msg_ts_ms, now_ms, current,
        )

    return (current - last_msg_ts_ms) < stale_ms
'''


def _indent(text, prefix="    "):
    return "\n".join((prefix + line) if line else line for line in text.split("\n"))


def render_lib_source(
    class_name,
    source_id,
    name_map,
    wanted,
    stale_after_ms,
    liveness_hook,
    source,
    generated_at,
    generator_version,
):
    """Render the `ExternalHardware` subclass source (D-02, D-13, D-16, D-17).

    `name_map` is `dlc_link.names.build_name_map`'s output, in selection order.
    `liveness_hook` is `"clock-consistent"` (default; emits the D-49..D-51 workaround) or
    `"substrate-default"` (emits none).
    """
    module_doc_text = "\n".join(
        [
            "Generated by dlc-link-generate v{} on {}.".format(generator_version, generated_at),
            "Source format: {!r}, engine: {!r}.".format(source.source_format, source.engine),
            "Config path: {!r} (sha256={!r}).".format(source.path, source.sha256),
            "Multianimal project: {!r}.".format(source.multianimal),
            "source_id: {!r}.".format(source_id),
            "Selected bodyparts: {!r}.".format(list(wanted)),
            "Coordinates are NORMALISED 0..1 (D-18).",
            (
                "liveness_hook: substrate-default (no override emitted)."
                if liveness_hook == "substrate-default"
                else "liveness_hook: clock-consistent override emitted (workaround for a "
                "Phase 31 clock-domain defect, D-49..D-51 -- not a sanctioned exemption)."
            ),
        ]
    )
    module_doc_literal = repr(module_doc_text)

    example_bodypart, example_entry = next(iter(name_map.items()))
    example_likelihood = example_entry["signals"]["likelihood"]
    if example_entry["coords"]:
        example_x = example_entry["signals"]["x"]
        and_example = "{}() > 0.6 and {}() > 0.3".format(example_likelihood, example_x)
    else:
        and_example = "{}() > 0.6".format(example_likelihood)

    class_doc_text = "\n".join(
        [
            "DeepLabCut-keypoint-backed ExternalHardware lib, generated -- do not hand-edit.",
            "",
            "Likelihood signals use stale_policy=\"return_default\" (default=0.0): 0.0",
            "genuinely means \"no confidence\" and is therefore safe in BOTH comparison",
            "directions. Coordinate signals use stale_policy=\"hold_last\": stale_policy=",
            "\"return_none\" raises TypeError out of the FDA's unguarded comparison and no",
            "numeric sentinel is safe both ways, so safety comes from ANDing every",
            "coordinate condition with that keypoint's own likelihood signal (D-17):",
            "",
            "    {}".format(and_example),
        ]
    )
    class_doc_literal = repr(class_doc_text)

    lines = [
        module_doc_literal,
        "",
        "from autopilot.hardware.external_hardware import ExternalHardware, signal",
        "",
        "",
        "class {}(ExternalHardware):".format(class_name),
        "    {}".format(class_doc_literal),
        "",
        "    # No release() override: ExternalHardware.release() already implements",
        "    # teardown (Task.end() calls it unconditionally); overriding it would break it.",
        "    # No command-decorated methods: there is no Pi-side CMD-send implementation",
        "    # anywhere in the autopilot tree, so an emitted command would be dead code",
        "    # the researcher would reasonably expect to work.",
        "    # No event-decorated methods: not needed for keypoint likelihood/coordinate signals.",
        "",
    ]

    if liveness_hook == "clock-consistent":
        lines.append(_indent(LIVENESS_HOOK_METHOD))
        lines.append("")

    for _bodypart, entry in name_map.items():
        likelihood_name = entry["signals"]["likelihood"]
        lines.append(
            "    # likelihood: return_default/0.0 is safe in both comparison directions\n"
            "    # (0.0 genuinely means \"no confidence\"); it is the guard that makes the\n"
            "    # matching coordinate usable at all (D-17).\n"
            "    @signal(default=0.0, stale_after_ms={}, stale_policy=\"return_default\")\n"
            "    def {}(self) -> float:\n"
            "        pass\n".format(stale_after_ms, likelihood_name)
        )
        if entry["coords"]:
            for axis in ("x", "y"):
                axis_name = entry["signals"][axis]
                lines.append(
                    "    # coordinate: hold_last -- return_none raises TypeError out of\n"
                    "    # the FDA's unguarded comparison; safety comes from ANDing this\n"
                    "    # signal with the keypoint's own likelihood signal above (D-17).\n"
                    "    @signal(default=0.0, stale_after_ms={}, stale_policy=\"hold_last\")\n"
                    "    def {}(self) -> float:\n"
                    "        pass\n".format(stale_after_ms, axis_name)
                )

    return "\n".join(lines) + "\n"


def render_signal_map(
    source_id,
    class_name,
    name_map,
    wanted,
    bodypart_class,
    stale_after_ms,
    source,
    pose_order,
    pose_order_source,
    lib_sha256,
    generated_at,
    generator_version,
):
    """Render the paired `<source_id>_signals.py` module the adapter IMPORTS (D-12).

    Every value is emitted via `repr()` as a standalone `NAME = repr(value)` statement --
    never embedded inside hand-written prose -- so no researcher-controlled string (a
    bodypart name, a config path) can corrupt the surrounding source regardless of its
    content. `LIB_SHA256` is the anti-divergence device D-12 demands: the adapter can
    assert the map it imported was generated alongside the lib that is actually deployed.
    """
    lines = [
        '"""GENERATED by dlc-link-generate v{} on {} -- DO NOT HAND-EDIT.'.format(
            generator_version, generated_at
        ),
        "",
        "The adapter (plan 35-04) IMPORTS this module rather than re-deriving names: an",
        "undeclared name is dropped Pi-side as unknown_name and is invisible from the",
        "sender's point of view (D-12). LIB_SHA256 pairs this map with the exact lib",
        "source emitted by the same generator invocation.",
        '"""',
        "",
        "SOURCE_ID = {!r}".format(source_id),
        "CLASS_NAME = {!r}".format(class_name),
        "BODYPARTS = {!r}".format(list(wanted)),
        "SIGNALS = {!r}".format(dict(name_map)),
        "SIGNAL_NAMES = {!r}".format(flat_signal_names(name_map)),
        "STALE_AFTER_MS = {!r}".format(stale_after_ms),
        "ENGINE = {!r}".format(source.engine),
        "SOURCE_FORMAT = {!r}".format(source.source_format),
        "CONFIG_PATH = {!r}".format(source.path),
        "CONFIG_SHA256 = {!r}".format(source.sha256),
        "GENERATED_AT = {!r}".format(generated_at),
        "GENERATOR_VERSION = {!r}".format(generator_version),
        "POSE_ORDER = {!r}".format(list(pose_order)),
        "POSE_ORDER_SOURCE = {!r}".format(pose_order_source),
        "BODYPART_CLASS = {!r}".format(dict(bodypart_class)),
        "LIB_SHA256 = {!r}".format(lib_sha256),
        "",
    ]
    return "\n".join(lines) + "\n"
