FROM python:3.11-slim

WORKDIR /orchestrator

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY orchestrator /orchestrator/orchestrator

CMD ["python", "-m", "orchestrator.main"]
