# GENERATED by dlc-link-relay --print supervisor (dlc_link.acquire_supervisor).
# Hand edits drift from the generator -- regenerate instead of editing this file.
# See dlc_link/RUNBOOK.md, ACQUISITION section, for what each piece is for.

$ff = "$env:USERPROFILE\ffmpeg\ffmpeg-9.0.1-essentials_build\bin\ffmpeg.exe"
$wd = "."
$lg = "log"
$maxRestarts = 5
$restartDelaySec = 5.0

# The ffmpeg argument array. Each line stays short on purpose -- a long single
# line wraps on paste in a Windows terminal, which cost two real failures in the
# 2026-09-10 rig session (38-HARDWARE-VALIDATION.md, rule 3, defect 8.3).
$t0 = '[f=segment:reset_timestamps=1:segment_format=matroska:segment_time=20:strftime=1]m'
$t0 += 'ics-acq-%Y%m%d-%H%M%S.mkv|[f=mpjpeg:onfail=ignore]tcp://198.51.100.7:9001'
$a=@('-hide_banner','-f','dshow','-rtbufsize','100M','-i','video=Generic Video Device')
$a+=@('-map','0:v','-c:v','mjpeg','-q:v','5','-fps_mode','passthrough','-f','tee',$t0)

New-Item -ItemType Directory -Force -Path $wd | Out-Null
Push-Location $wd
New-Item -ItemType Directory -Force -Path $lg | Out-Null

$attempt = 0
$lastExit = $null
while ($attempt -lt $maxRestarts) {
    $attempt++
    if ($attempt -gt 1) {
        Write-Host "restart attempt $attempt after previous exit code $lastExit"
        Start-Sleep -Seconds $restartDelaySec
    }
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    # ffmpeg writes this log itself; level=32 (info) keeps `frame dropped` lines.
    $env:FFREPORT = "file=$lg/acq-$stamp-attempt${attempt}.log:level=32"
    & $ff @a
    $lastExit = $LASTEXITCODE
    if ($lastExit -eq 0) { break }
}
Pop-Location
Write-Host "stopped after $attempt attempt(s); last exit code $lastExit; logs in $lg"
Write-Host "segment directory: $wd"
Write-Host "log directory: $lg"
