# GENERATED by dlc-link-relay --print supervisor (dlc_link.acquire_supervisor).
# Hand edits drift from the generator -- regenerate instead of editing this file.
# See dlc_link/RUNBOOK.md, ACQUISITION section, for what each piece is for.

$ff = "$env:USERPROFILE\ffmpeg\ffmpeg-9.0.1-essentials_build\bin\ffmpeg.exe"
$wd = "."
$lg = ".\log"
$maxRestarts = 5
$restartDelaySec = 5.0

# The ffmpeg argument array. Each line stays short on purpose -- a long single
# line wraps on paste in a Windows terminal, which cost two real failures in the
# 2026-09-10 rig session (38-HARDWARE-VALIDATION.md, rule 3, defect 8.3).
$t0 = '[f=segment:reset_timestamps=1:segment_format=matroska:segment_time=20:strftime=1]m'
$t0 += 'ics-acq-%Y%m%d-%H%M%S.mkv|[f=mpjpeg:onfail=ignore]tcp://198.51.100.7:9001'
$a=@('-hide_banner','-f','dshow','-rtbufsize','100M','-i','video=Generic Video Device')
$a+=@('-c:v','mjpeg','-q:v','5','-fps_mode','passthrough','-f','tee',$t0)

New-Item -ItemType Directory -Force -Path $wd,$lg | Out-Null

$attempt = 0
$lastExit = $null
while ($attempt -lt $maxRestarts) {
    $attempt++
    if ($attempt -gt 1) {
        Write-Host "restart attempt $attempt after previous exit code $lastExit"
        Start-Sleep -Seconds $restartDelaySec
    }
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $err = Join-Path $lg "acq-$stamp-attempt$attempt.err.log"
    $sp = @{FilePath=$ff; ArgumentList=$a; WorkingDirectory=$wd}
    $proc = Start-Process @sp -NoNewWindow -Wait -PassThru -RedirectStandardError $err
    $lastExit = $proc.ExitCode
}
Write-Host "gave up after $attempt attempts; last exit code $lastExit; log $err"
Write-Host "segment directory: $wd"
Write-Host "log directory: $lg"
