"Generated by dlc-link-generate v0.1.0 on 2026-08-31T12:24:38Z.\nSource format: 'config.yaml', engine: 'pytorch'.\nConfig path: 'dlc_link/tests/fixtures/dlc3_multianimal_config.yaml' (sha256='d4176a8e9c58154cc9885899f2829ef58ece1ef6047533bb5a39eccea0662843').\nMultianimal project: True.\nsource_id: 'dlc_cam1'.\nSelected bodyparts: ['LED_on', 'LED_off'].\nCoordinates are NORMALISED 0..1 (D-18).\nliveness_hook: clock-consistent override emitted (workaround for a Phase 31 clock-domain defect, D-49..D-51 -- not a sanctioned exemption)."

from autopilot.hardware.external_hardware import ExternalHardware, signal


class DlcCam1(ExternalHardware):
    'DeepLabCut-keypoint-backed ExternalHardware lib, generated -- do not hand-edit.\n\nLikelihood signals use stale_policy="return_default" (default=0.0): 0.0\ngenuinely means "no confidence" and is therefore safe in BOTH comparison\ndirections. Coordinate signals use stale_policy="hold_last": stale_policy=\n"return_none" raises TypeError out of the FDA\'s unguarded comparison and no\nnumeric sentinel is safe both ways, so safety comes from ANDing every\ncoordinate condition with that keypoint\'s own likelihood signal (D-17):\n\n    led_on_likelihood() > 0.6 and led_on_x() > 0.3'

    # No release() override: ExternalHardware.release() already implements
    # teardown (Task.end() calls it unconditionally); overriding it would break it.
    # No command-decorated methods: there is no Pi-side CMD-send implementation
    # anywhere in the autopilot tree, so an emitted command would be dead code
    # the researcher would reasonably expect to work.
    # No event-decorated methods: not needed for keypoint likelihood/coordinate signals.

    def liveness_hook(self, last_msg_ts_ms, now_ms, stale_ms):
        """The passed-in `now_ms` is not used because it is `time.time()`-derived
        (`external_hardware_binding.py:_now_ms()`) while `last_msg_ts_ms` is one-clock-derived on
        the mics_core stack, so subtracting them crosses clock domains; on the pi-mirror stack this
        hook is numerically identical to `default_liveness` because both sides are `time.time()`
        there (`pi-mirror/.../external_hardware_ingress.py` stamps `int(time.time() * 1000)`).
        """
        if last_msg_ts_ms is None:
            return False
        try:
            # Imported here, not at module scope: a module-level import would run at lib-exec
            # time (this file is `exec`'d from `hardware_lib_versions.source_code`), before
            # `autopilot.hardware.external_hardware_ingress` is necessarily importable.
            from autopilot.hardware.external_hardware_ingress import now_ms as ingress_now_ms
            current = ingress_now_ms()
        except Exception:
            # Degrade to the substrate default rather than raising into the LivenessPoller,
            # which runs on its own daemon thread but whose exceptions would otherwise silently
            # stop the poll (T-35-06).
            current = now_ms

        if not getattr(self, "_liveness_hook_logged_once", False):
            self._liveness_hook_logged_once = True
            # One-shot diagnostic: measures the actual offset between the two clocks on a real
            # rig run, landing in the pilot journal via self.logger (never print -- this runs
            # inside the pilot process, not a script with a controlling terminal).
            self.logger.warning(
                "liveness_hook: one-shot clock check (last_msg_ts_ms=%s, now_ms=%s, "
                "ingress_now_ms=%s)", last_msg_ts_ms, now_ms, current,
            )

        return (current - last_msg_ts_ms) < stale_ms


    # likelihood: return_default/0.0 is safe in both comparison directions
    # (0.0 genuinely means "no confidence"); it is the guard that makes the
    # matching coordinate usable at all (D-17).
    @signal(default=0.0, stale_after_ms=200, stale_policy="return_default")
    def led_on_likelihood(self) -> float:
        pass

    # coordinate: hold_last -- return_none raises TypeError out of
    # the FDA's unguarded comparison; safety comes from ANDing this
    # signal with the keypoint's own likelihood signal above (D-17).
    @signal(default=0.0, stale_after_ms=200, stale_policy="hold_last")
    def led_on_x(self) -> float:
        pass

    # coordinate: hold_last -- return_none raises TypeError out of
    # the FDA's unguarded comparison; safety comes from ANDing this
    # signal with the keypoint's own likelihood signal above (D-17).
    @signal(default=0.0, stale_after_ms=200, stale_policy="hold_last")
    def led_on_y(self) -> float:
        pass

    # likelihood: return_default/0.0 is safe in both comparison directions
    # (0.0 genuinely means "no confidence"); it is the guard that makes the
    # matching coordinate usable at all (D-17).
    @signal(default=0.0, stale_after_ms=200, stale_policy="return_default")
    def led_off_likelihood(self) -> float:
        pass

