"""GENERATED by dlc-link-generate v0.1.0 on 2026-08-31T12:24:38Z -- DO NOT HAND-EDIT.

The adapter (plan 35-04) IMPORTS this module rather than re-deriving names: an
undeclared name is dropped Pi-side as unknown_name and is invisible from the
sender's point of view (D-12). LIB_SHA256 pairs this map with the exact lib
source emitted by the same generator invocation.
"""

SOURCE_ID = 'dlc_cam1'
CLASS_NAME = 'DlcCam1'
BODYPARTS = ['LED_on', 'LED_off']
SIGNALS = {'LED_on': {'ident': 'led_on', 'index': 15, 'coords': True, 'signals': {'likelihood': 'led_on_likelihood', 'x': 'led_on_x', 'y': 'led_on_y'}}, 'LED_off': {'ident': 'led_off', 'index': 14, 'coords': False, 'signals': {'likelihood': 'led_off_likelihood'}}}
SIGNAL_NAMES = ['led_off_likelihood', 'led_on_likelihood', 'led_on_x', 'led_on_y']
STALE_AFTER_MS = 200
ENGINE = 'pytorch'
SOURCE_FORMAT = 'config.yaml'
CONFIG_PATH = 'dlc_link/tests/fixtures/dlc3_multianimal_config.yaml'
CONFIG_SHA256 = 'd4176a8e9c58154cc9885899f2829ef58ece1ef6047533bb5a39eccea0662843'
GENERATED_AT = '2026-08-31T12:24:38Z'
GENERATOR_VERSION = '0.1.0'
POSE_ORDER = ['nose', 'L_ear', 'L_eye', 'R_eye', 'R_ear', 'head_center', 'head_end', 'L_side', 'tail', 'R_side', 'NW', 'NE', 'SE', 'SW', 'LED_off', 'LED_on', 'Mic1_middle', 'Mic1_end', 'Mic2_middle', 'Mic2_end', 'Mic3_middle', 'Mic3_end', 'Mic4_middle', 'Mic4_end', 'Mic5_middle', 'Mic5_end', 'Mic6_middle', 'Mic6_end', 'Mic7_middle', 'Mic7_end', 'Mic8_middle', 'Mic8_end']
POSE_ORDER_SOURCE = 'config-declared-UNVERIFIED'
BODYPART_CLASS = {'LED_on': 'unique', 'LED_off': 'unique'}
LIB_SHA256 = '184496c8b5b54ca4a0d7623049d1a2de5c47539d3007bd58ea728e745067840a'

