"""Frozen wire-format corpus for `mics_link.wire` (Phase 34, Plan 01).

Generated by `generate_golden.py` against the CANONICAL Pi reference module named in
`pi_reference.py` (`~/mics_core/autopilot/autopilot/hardware/external_hardware_wire.py`,
verified byte-identical to `~/pi-mirror`'s copy at generation time, 2026-08-30). This file
is NEVER hand-edited — to refresh it, re-run `python3 tests/generate_golden.py` and paste
its output back in here.

`fields` is an ORDERED list of (name, value) pairs, not a dict, so the kwarg insertion
order that matters for byte parity (decision 4 in 34-01-PLAN.md) is explicit in the data,
not merely implied by dict literal order.
"""

GOLDEN_FRAMES = [
    {
        "kind": "SIG",
        "fields": [("ts_src", 1700000000123), ("seq", 12), ("sig", "left_paw_x"), ("v", 0.7)],
        "hex": "85a16ba3534947a674735f737263cf0000018bcfe5687ba37365710ca3736967aa6c6566745f7061775f78a176cb3fe6666666666666",
        "note": "float value",
    },
    {
        "kind": "SIG",
        "fields": [("ts_src", 1700000000124), ("seq", 13), ("sig", "trial_count"), ("v", 3)],
        "hex": "85a16ba3534947a674735f737263cf0000018bcfe5687ca37365710da3736967ab747269616c5f636f756e74a17603",
        "note": "int value",
    },
    {
        "kind": "SIG",
        "fields": [("ts_src", 1700000000125), ("seq", 14), ("sig", "door_open"), ("v", True)],
        "hex": "85a16ba3534947a674735f737263cf0000018bcfe5687da37365710ea3736967a9646f6f725f6f70656ea176c3",
        "note": "bool value (must NOT pack as int)",
    },
    {
        "kind": "SIG",
        "fields": [("ts_src", 1700000000126), ("seq", 15), ("sig", "state_name"), ("v", "active")],
        "hex": "85a16ba3534947a674735f737263cf0000018bcfe5687ea37365710fa3736967aa73746174655f6e616d65a176a6616374697665",
        "note": "str value",
    },
    {
        "kind": "EVT",
        "fields": [
            ("ts_src", 1700000000200),
            ("seq", 20),
            ("evt", "object_detected"),
            ("p", {"object": "paw", "confidence": 0.9}),
        ],
        "hex": "85a16ba3455654a674735f737263cf0000018bcfe568c8a373657114a3657674af6f626a6563745f6465746563746564a17082a66f626a656374a3706177aa636f6e666964656e6365cb3feccccccccccccd",
        "note": "event with dict payload",
    },
    {
        "kind": "HB",
        "fields": [("ts_src", 1700000000300), ("seq", 99)],
        "hex": "83a16ba24842a674735f737263cf0000018bcfe5692ca373657163",
        "note": "heartbeat, no other fields",
    },
    {
        "kind": "ACK",
        "fields": [("ts_src", 1700000000400), ("cmd_id", "cmd-001"), ("result", {"status": "ok"})],
        "hex": "84a16ba341434ba674735f737263cf0000018bcfe56990a6636d645f6964a7636d642d303031a6726573756c7481a6737461747573a26f6b",
        "note": "command result, NO seq field",
    },
    {
        "kind": "CMD",
        "fields": [
            ("ts_pi", 1700000000500),
            ("cmd_id", "cmd-002"),
            ("name", "set_reward"),
            ("args", {"amount": 1}),
        ],
        "hex": "85a16ba3434d44a574735f7069cf0000018bcfe569f4a6636d645f6964a7636d642d303032a46e616d65aa7365745f726577617264a46172677381a6616d6f756e7401",
        "note": "Pi -> SDK only, decode-only direction",
    },
]
